DROP TABLE IF EXISTS BOOK_AUTHOR;
DROP TABLE IF EXISTS BOOK_GENRE;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON(
PERSON_ID INT(11) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
SUR_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY ("PERSON_ID")
);

CREATE TABLE GENRE(
GENRE_ID       INT(11)  NOT NULL AUTO_INCREMENT COMMENT 'GENRE ID FIELD',
GENRE_NAME     VARCHAR(255) COMMENT 'GENRE NAME FIELD',
PRIMARY KEY(`GENRE_ID`)
);


CREATE TABLE AUTHOR(
AUTHOR_ID      INT(11)  NOT NULL AUTO_INCREMENT COMMENT 'AUTHOR ID FIELD',
AUTHOR_NAME    VARCHAR(255) COMMENT 'AUTHOR NAME FIELD',
AUTHOR_SURNAME VARCHAR(255) COMMENT 'AUTHOR SURNAME FIELD',
PRIMARY KEY(`AUTHOR_ID`)
);


CREATE TABLE BOOK(
BOOK_ID   INT(11) NOT NULL AUTO_INCREMENT,
BOOK_NAME varchar(80) NOT NULL,
PRIMARY KEY (`BOOK_ID`)
);


CREATE TABLE BOOK_AUTHOR (
BOOK_ID INT(11),
AUTHOR_ID INT(11),
PRIMARY KEY (`BOOK_ID`,`AUTHOR_ID`),
CONSTRAINT `BOOK_AUTHOR_ID_FK`
FOREIGN KEY(`BOOK_ID`)
REFERENCES `BOOK`(`BOOK_ID`),
CONSTRAINT `AUTHOR_BOOK_ID_FK`
FOREIGN KEY(`AUTHOR_ID`)
REFERENCES `AUTHOR`(`AUTHOR_ID`)
);

CREATE TABLE BOOK_GENRE (
BOOK_ID INT(11),
GENRE_ID INT(11),
PRIMARY KEY (`BOOK_ID`,`GENRE_ID`),
CONSTRAINT `BOOK_GENRE_ID_FK`
FOREIGN KEY(`BOOK_ID`)
REFERENCES `BOOK`(`BOOK_ID`),
CONSTRAINT `GENRE_BOOK_ID_FK`
FOREIGN KEY(`GENRE_ID`)
REFERENCES `GENRE`(`GENRE_ID`)
);
