version: "3.8"
services:
  mongo111:
    image: mongo:latest
    container_name: mongodb111
    hostname: mongodb111
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    volumes:
      - ./mongodb11/log/:/var/log/mongodb/
      - ./db-init/:/docker-entrypoint-initdb.d
      - ./mongodb11/db:/data/db
    ports:
      - "27132:27017"
    command: ["--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all"]
    networks:
      - hw111_bridge
    restart: always
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongo-express111:
    image: mongo-express
    container_name: mongo-express111
    hostname: mongoexpress111
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo111
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - 8111:8081
    restart: always
    networks:
      - hw111_bridge

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6390:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    #logging:
    #  driver: none
    restart: always
    networks:
      - hw111_bridge
networks:
  hw111_bridge:
    name: hw111_bridge
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
