DROP SEQUENCE  comments_seq  IF EXISTS ;
DROP SEQUENCE  author_seq  IF EXISTS ;
DROP SEQUENCE  book_seq  IF EXISTS ;
DROP SEQUENCE  genre_seq  IF EXISTS ;
DROP SEQUENCE  person_seq  IF EXISTS ;

DROP TABLE BOOK_AUTHOR_REF IF EXISTS;
DROP TABLE BOOK_GENRE_REF IF EXISTS;
DROP TABLE BOOK_COMMENTS IF EXISTS;
DROP TABLE AUTHOR IF EXISTS;
DROP TABLE BOOK IF EXISTS;
DROP TABLE GENRE IF EXISTS;
DROP TABLE PERSON IF EXISTS;