DROP TABLE IF EXISTS BOOK_AUTHOR_REF;
DROP TABLE IF EXISTS BOOK_GENRE_REF;

DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;

DROP SEQUENCE IF EXISTS person_seq;
DROP SEQUENCE IF EXISTS book_seq;
DROP SEQUENCE IF EXISTS author_seq;
DROP SEQUENCE IF EXISTS genre_seq;

CREATE SEQUENCE person_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
;

CREATE TABLE PERSON(
  PERSON_ID BIGINT default person_seq.nextval primary key,
  NAME VARCHAR(255) NOT NULL,
  SUR_NAME VARCHAR(255) NOT NULL
);

CREATE SEQUENCE book_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
;

CREATE TABLE BOOK(
  BOOK_ID BIGINT default book_seq.nextval primary key,
  NAME VARCHAR(255) NOT NULL,
  BOOK_NAME VARCHAR(255) NOT NULL
);

CREATE SEQUENCE genre_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
;

CREATE TABLE GENRE(
  GENRE_ID BIGINT default genre_seq.nextval primary key,
  GENRE_NAME VARCHAR(255) NOT NULL
);


CREATE SEQUENCE author_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
;

CREATE TABLE AUTHOR(
  AUTHOR_ID BIGINT default author_seq.nextval primary key,
  AUTHOR_NAME VARCHAR(255) NOT NULL,
  AUTHOR_SURNAME VARCHAR(255) NOT NULL
);


CREATE TABLE BOOK_GENRE_REF (
  BOOK_ID BIGINT NOT NULL,
  GENRE_ID BIGINT NOT NULL,
  PRIMARY KEY (`BOOK_ID`,`GENRE_ID`),
  CONSTRAINT `BOOK_GENRE_ID_FK`
    FOREIGN KEY(`BOOK_ID`)
    REFERENCES `BOOK`(`BOOK_ID`),
  CONSTRAINT `GENRE_BOOK_ID_FK`
    FOREIGN KEY(`GENRE_ID`)
    REFERENCES `GENRE`(`GENRE_ID`)
);


CREATE TABLE BOOK_AUTHOR_REF (
  BOOK_ID BIGINT NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  PRIMARY KEY (`BOOK_ID`,`AUTHOR_ID`),
  CONSTRAINT `BOOK_AUTHOR_ID_FK`
    FOREIGN KEY(`BOOK_ID`)
    REFERENCES `BOOK`(`BOOK_ID`),
  CONSTRAINT `AUTHOR_BOOK_ID_FK`
    FOREIGN KEY(`AUTHOR_ID`)
    REFERENCES `AUTHOR`(`AUTHOR_ID`)
);


