DROP TABLE IF EXISTS PERSON;
DROP SEQUENCE IF EXISTS person_seq;

CREATE SEQUENCE person_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
;

CREATE TABLE PERSON(
  PERSON_ID BIGINT default person_seq.nextval primary key,
  NAME VARCHAR(255) NOT NULL,
  SUR_NAME VARCHAR(255) NOT NULL
);