mongo:
  username: sergio
  password: 123456
  host: localhost
  port: 27117
  db: test_library
  replica_name: rs0
  auth:
    db: admin
    mechanism: SCRAM-SHA-256
  ssl: false
spring:
  data:
    mongodb:
      uri: mongodb://${mongo.username}:${mongo.password}@${mongo.host}:${mongo.port}/${mongo.db}?ssl=${mongo.ssl}&authSource=${mongo.auth.db}&authMechanism=${mongo.auth.mechanism}&replicaSet=${mongo.replica_name}
      auto-index-creation: true

  profiles:
    active: prod #prod,init
  main:
    banner-mode: "off"

---

spring:
  profiles: prod

---

spring:
  profiles: init